export default [
    {
        id: 0,
        name: 'Galaxy Watch',
        price: 119,
        img: '/products/product0.jpg',
        category: ["smart", "digital", "classic", "kids"],
        sale: false,
    },
    {
        id: 1,
        name: 'Smart Watch 4',
        price: 229,
        img: '/products/product1.jpg',
        category: ["smart", "digital", "kids"],
        sale: true,
    },
    {
        id: 2,
        name: 'Apple Watch Series 7',
        price: 399,
        img: '/products/product2.jpg',
        category: ["smart", "classic"],
        sale: false,
    },
    {
        id: 3,
        name: 'Fitbit Sense',
        price: 199,
        img: '/products/product3.jpg',
        category: ["digital", "kids"],
        sale: true,
    },
    {
        id: 4,
        name: 'Garmin Forerunner 945',
        price: 499,
        img: '/products/product4.jpg',
        category: ["classic", "digital"],
        sale: false,
    },
    {
        id: 5,
        name: 'Amazfit GTS 3',
        price: 149,
        img: '/products/product5.jpg',
        category: ["smart", "classic"],
        sale: true,
    },
    {
        id: 6,
        name: 'Fossil Gen 5',
        price: 295,
        img: '/products/product6.jpg',
        category: ["classic", "smart"],
        sale: true,
    },
    {
        id: 7,
        name: 'TicWatch Pro 3',
        price: 249,
        img: '/products/product7.jpg',
        category: ["digital", "classic"],
        sale: false,
    },
    {
        id: 8,
        name: 'Huawei Watch GT 3',
        price: 179,
        img: '/products/product8.jpg',
        category: ["smart", "classic"],
        sale: true,
    },
    {
        id: 9,
        name: 'Withings Steel HR',
        price: 129,
        img: '/products/product9.jpg',
        category: ["classic", "kids"],
        sale: false,
    },
    {
        id: 10,
        name: 'Suunto 7',
        price: 399,
        img: '/products/product10.jpg',
        category: ["smart", "digital", "kids"],
        sale: true,
    },
]